name: demo_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.1.2
  http: ^0.13.5
  url_launcher: ^6.0.8
  connectivity_plus: ^1.1.0
  sqflite: ^2.0.0+4
  intl: ^0.17.0
  device_info_plus: ^8.2.0
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0


flutter_icons:
  android: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: sono-bold
      fonts:
        - asset: assets/fonts/sono-bold.ttf
    - family: sono-medium
      fonts:
        - asset: assets/fonts/sono-medium.ttf
    - family: sono-regular
      fonts:
        - asset: assets/fonts/sono-regular.ttf